# Diretórios principais
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

# Configuração de build
[build]
  bin = "./tmp/main"  # sem .exe no Linux/WSL
  cmd = "templ generate && go build -o ./tmp/main ./cmd/server/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go", "_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

# Cores no terminal
[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

# Logs
[log]
  main_only = false
  time = false

# Configurações misc
[misc]
  clean_on_exit = false

# Comportamento da tela
[screen]
  clear_on_rebuild = false
  keep_scroll = true
